apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: cm9vdA==        # root      (echo -n "root" | base64)
  password: bWlvbGFwYXNz   # miolapass (echo -n "miolapass" | base64)
